italia/bootstrap-italia

- src/js/plugins/custom-select.js
Refactoring of code is done, many times "var" keyword was used which is being eliminated so that we can decrease the load time of the js file.
> Refactored the code

- docs/utilities/icone.md
In the docs there was no mention of the `icon-white` class that can be applied to SVG icons in order to render them in white, but it works.
> Add example for icon-white in the docs

- docs/assets/src/scss/_sidebar.scss
L'accordion aperto ottiene tutto lo spazio necessario in altezza senza un'ulteriore scrollbar.
> tolto overflow-y: auto dal breakpoint

- src/scss/custom/_headerslim.scss
> Give a right color to the icons in the slimheader

- src/scss/custom/_buttons.scss
- src/scss/custom/_headerslim.scss
- src/scss/utilities/colors_vars.scss
- src/scss/utilities/icons.scss
Impostato un colore di default in ogni proprio contesto (dropdown, slimheader, btn-icon, rounded-icon)
Le classi colore per le icone, inoltre, se espressamente settate, fanno l'override del colore in ogni contesto attraverso l'uso di `!important`. In questo specifico caso è tollerabile perchè è una regola isolata che non genera modifiche involontarie ad altri contesti e lo stesso Bootstrap promuove e utilizza come tecnica nell'impostazione di colori o stili specifici.
> FIX colore icona in diversi contesti

- src/js/plugins/select.js
- src/scss/custom/_form-select.scss
Fixes #293 editing the DOM through jQuery.
There still are some open issues regarding the multi-select, select with checkboxes and the attribute `x-placement` which is created by the library after the first opening of the selection.
This commit however resolve most of the reportings produced by checkers.
> BS select W3C and WCAG 2.0 compliant

- src/scss/custom/mixins/_text-emphasis.scss
Impostata eccezione nel mixin per gestire il colore $white come colore bianco effettivo e non con il darken() al 15%
> eccezione del colore bianco per il text-emphasis-variant senza darken

- src/js/plugins/forms.js
Aggiunge per ora un listener (`changed.bs.form-control`) per poter sbloccare la label come segnalato nella issue #347 da @ilbassa. Vedremo poi di sistemarlo in modo più consistente.
> Aggiunge listener per gestire il refresh della label

- gulpfile.js
I pacchetti, sia bundle che non, quando caricati generano il seguente errore (Firefox):
```
bootstrap-italia.min.js:20:22
SyntaxError: missing ] after element list
note: [ opened at line 20, column 14
```
I pacchetti contengono la stringa `[object Object]` nell'ultimo blocco `+function() { ... }`
Questo PR fissa questo problema.
Secondo la documentazione di `gulp-append-prepend`, infatti, la funzione `prependText()` come secondo parametro accetta una stringa, non un oggetto.
> Fix gulp prependText usage

- docs/form/input.md
- src/js/plugins/password-strength-meter/password-strength-meter.js
Aggiunge il supporto alla personalizzazione delle stringhe associate alla componente `password-strength-meter`.
> Support password-strength-meter customization

- src/scss/_variables.scss
- src/scss/custom/_form-toggles.scss
- src/scss/custom/_forms.scss
- src/scss/utilities/focus.scss
La classe `focus--keyboard` non è utilizzata per segnalare il focus da tastiera, così gli elementi che ricevono il focus hanno lo stile predefinito del browser. Questa PR assegna lo stile della classe `focus--keyboard` agli elementi che ricevono il focus.
> Add proper style to focused elements

- src/js/plugins/transfer.js
Fixes #403 
Sposta il check `listToCheckControl.length == listToCheck.length` in maniera tale che non vada a influenzare l'abilitazione del pulsante(che viene abilitato sempre se c'è almeno un elemento selezionato, come dovrebbe), ma solo lo stato della checkbox nell'header.
> Fix Issue #403 transfer disabled on single-element Transfer

- docs/menu-di-navigazione/header.md
- src/scss/custom/_headerslim.scss
- src/scss/custom/_headerslimtheme.scss
Aggiunge `list-item` per consistenza alle `link-list` presenti nello slim header.
È potenzialmente un breaking change, per cui dobbiamo capire se/come/quando mergiarlo e versionarlo.
> Fix header class names

- docs/componenti/chips.md
Ho modificato il file relativo alla sezione "chips" aggiungendo il display dei colori standard di Bootstrap.
Closes #402
> (docs) Aggiunti colori al componente Chips

- src/scss/custom/_timepicker.scss
This PR removes a forced behaviour of `aria-hidden` which is replacing the correct browser side interpretation. 
I also found a reference to `aria-hidden` here: https://github.com/italia/bootstrap-italia/blob/58581919e8c69b3a5018e68b2619d7c44e365d43/src/scss/custom/_form-datepicker.scss#L340-L352 but I leave the last word about this to you @francescozaia 
Fixes #419
> Remove rule forcing aria-hidden behaviour

- docs/esempi/template-vuoto/index.html
- docs/menu-di-navigazione/header.md
- src/scss/custom/_headerslim.scss
Soluzione proposta per il fix dell'issue #416 
Fixes #416 
Ho modificato il codice HTML, sia nella documentazione che negli esempi, sostituendo il tag "button" con il tag "a".
Nelle linee di codice modificate ho rimosso 'type=button' (raccomandazioni W3C)
Ho modificato lo stile aggiungendo un selettore e mantenendo il vecchio selettore per retrocompatibilità.
Maggiori dettagli nel diff allegato.
**N.B.**. Non ho effettuato verifiche su OSX e iOS. Su linux, Android, e Windos sì. [http://arturu.it/test-bi/test/test-patch-button.html](http://arturu.it/test-bi/test/test-patch-button.html)
> Un tag "button" non può contenere un attributo "href" #416

- src/js/plugins/timepicker.js
Trigger change on 
$input.val(timeH + ':' + timeM).change()
Trigger change on input change
Invocazione change dopo la modifica dell input
- [ X] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [X ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ X] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ X] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile …
> Trigger change on input change

- gulpfile.js
Fixes #433 - in the js-bundle-min gulp task there is an extra anonymous function definition which prevents loading some of the components' code (i.e. the notification one).
> Fix #433 - Remove anonymous function scope in js-min task

- src/js/plugins/ie.js
Ho aggiunto un workaround per rendere globale la funzione isIe() nel caso in cui viene effettuato il build con webpack.
Ho aggiunto una linea di codice per rendere accessibile la funzione agli altri componenti in modo che non venga generato l'errore _isIe() is not defined_
Ho verificato che il codice introdotto non generi errori di compilazione o funzionamento. Ho compilato e caricato la modifica su questa installazione https://bi-branch-swiper.arturu.it/docs/form/input-numerico/#valuta . Il componente "Input Valuta" fa uso della funzione isIe().
- [x ] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [ x] Il codice è coerente con le [indicazioni di …
> isIe() non è definito se viene effettuato il build con webpack

- src/scss/custom/_thumbnav.scss
Fixed the flexbox CSS that was not working on Firefox, see the issue #465 
The layout engine could not infer correctly the dimensions of the thumbnails. So I tweaked a bit the CSS in such a way that the browser has all the box model's information to guess reliably the sizes. Fixes #465
> Fixed Thumbnav on Firefox, closes #465

- src/scss/bootstrap-italia.scss
- src/scss/custom/_print.scss
Ho aggiunto del CSS che mostra correttamente le checkbox selezionate anche quando la pagina viene stampata.
Mancando, ho creato un nuovo file `scss/custom/_print.scss` che aggiunge il codice necessario.
Fixes #428.
> Corretto lo stile dei checkbox se stampati

- _config.yml
- _config_production.yml
- _includes/favicons.html
- _includes/head.html
- browserconfig.xml
- package.json
- site.webmanifest
* Remove superfluous configuration
* Make browserconfig.xml and site.webmanifest respect baseurl
* Use the JEKYLL_ENV variable to set the environment, as it's the
standard method to do it
Fix #571.
> fix: cleanup baseurl configuration

- PULL_REQUEST_TEMPLATE.md
- README.EN.md
- README.md
- _data/examples.yml
- _includes/callout-danger-async-methods.md
Aggiornati i link alla documentazione di Bootstrap in modo che puntino alla versione corretta (4.5)
> Point links to Bootstrap 4.6 docs

- src/scss/custom/_forms.scss
I made a new PR since the previous one (#557) was uncorrectly from fork's master to upstream's master. I also applied the suggested changes.
Moving the actual HTML checkbox/radio button to the left to make it disappear from the screen leads the browser's native feedback box to also disappear (for example if the field is marked as required but the checkbox is not ticked). Setting `opacity: 0` instead of `left: -9999px` makes the native checkbox/radio button disappear without moving it outside of the screen so the feedback can be seen.
@gpeirolo also kindly suggested to move the invisible cbox/rb a bit to better align the browser's feedback box.
> Checkbox/radio button's required HTML feedback not visible

- src/scss/_variables.scss
- src/scss/custom/_skiplinks.scss
Fix #523.
Skiplinks: text & background contrast
> fix(core,a11y): skiplinks contrast

- docs/menu-di-navigazione/skiplinks.md
Fixes #543 
Aggiunta documentazione relativa all'utilizzo della navigazione delle pagine con tasto TAB in macOS per:
- Chrome
- Safari
- Firefox
> docs(a11y): skiplinks tab navigation instructions for macos

- src/scss/custom/_forms.scss
z-index dell'elemento .form-group label portato a 1
> fix(core): posizione label invisibile dietro input

- docs/componenti/modale.md
Fixes #555 
Modificato il codice degli esempi con un uso corretto dell'attributo aria-labelledby della modale associato al titolo della modale stessa.
> docs(a11y): implemented modal aria-labelledby in examples

- src/js/plugins/forms.js
Quando un campo di input ha il focus la label si sposta verso l'alto, questo comportamento è implementato in form.js e la selezione della label avviene con il metodo `siblings()`. Ho cambiato il metodo di selezione utilizzando l'associazione `for/id`.
Propongo la discussione di questo cambiamento in quanto penso che sia necessario sotto due aspetti:
- nei CMS alcune volte il campo `input` è racchiuso dentro a dei campi `div` - necessario per editor di testo, campi particolari, ecc - quindi viene meno la selezione come "fratelli" sullo stesso nodo;
- la selezione della label attraverso l'associazione `for/id` copre una casistica molto più ampia della selezione tra nodi fratelli.
**Nota**: Questa modifica potrebbe essere problematica per le applicazioni che ancora non associano la label al …
> fix(core,a11y): select label with for attribute instead of siblings.

- src/scss/utilities/focus.scss
Questa PR fixes #518
Ora, tutti gli elementi raggiunti tramite tab risultano bordati di arancione.
I bottoni se cliccati, mantengono il focus originale di bootstrap.
> fix(core): focus behaviour

- docs/componenti/dropdown.md
Fixes #542 
Aggiunto esempio dropdown con bottone `.btn-danger`.
Aggiunta classe `.no-toc` a due h3 degli esempi per escluderli dal menù di navigazione laterale.
> docs: dropdown examples and side navigation fix

- src/scss/custom/_navigation.scss
Fixes #525
La soluzione proposta avrebbe risolto il problema solo per la paginazione.
Bootstrap utilizza z-index specifici (1,2,3) per stati normail, hover o attivi di qualsiasi bottone.
Ho impostato lo z-index del menù aperto mobile a 100 in modo che si trovi sempre sopra agli elementi di pagina.
-docs/it/stabile/doc/service-design/accessibilita.html).
> fix(core): set mobile navbar z-index to 100 so it always stays on top

- docs/form/introduzione.md
Fixes #499 
Sistemato il testo "I messaggi di feedback possono..."
> docs: form validation copy correction

- src/scss/custom/_gridlist.scss
Fixes #453 
Modificato il CSS per risolvere bug di rendering di Safari.
Fix specifico per l'altezza delle immagini in IE11.
> fix(core): css solution for safari masonry bug plus ie11 fix

- docs/organizzare-i-contenuti/liste-di-link.md
- src/scss/custom/_linklist.scss
Revisione documentazione linklist ed aggiunta delle classi corrette per la posizione icona.
Ora, le classi necessarie per il posizionamento delle icone sono applicate al solo tag "a".
Classi:
icon-right: icona a desrtra
icon-left: icona a sinistra
> fix(core,docs): revisione documentazione linklist

- docs/menu-di-navigazione/toolbar.md
Fix #569
Rimossa l'icona chiudi disabilitata per evitare confusione.
> docs: rimozione icona chiudi da toolbar

- src/scss/custom/_gridlist.scss
Fixes #484 
Implementata masonry a 2 colonne per breakpoint sm ed md.
> fix(core):  2 columns masonry for tablet portrait

- src/scss/custom/_headerslim.scss
Fixes #435 
Inserito un selettore CSS più specifico per l'icona caret che indica l'apertura del dropdown.
Ora è possibile inserire icone nel dropdown senza che queste vengano ribaltate all'apertura.
> fix(core): specific selector for header slim dropdown

- docs/organizzare-i-contenuti/tabelle.md
Move content about responsive tables in the right section.
> fix(docs): wrong content for responsive tables

- docs/form/select.md
Add warning to documentation for select virtualscroll
> docs: add warning for select virtualscroll

- src/scss/custom/_headernavbartheme.scss
La modifica proposta corregge il bug che non consente la corretta visualizzazione dell'icona it-burger nel menù quando questo è in modalità light.
Modificata l'assegnazione del colore $navigation-light-text-color che avviene quando l'header centrale ha la classe theme-light. La modifica ricalca quella proposta del rif  [#35](https://github.com/italia/bootstrap-italia-next/issues/35)
> Modifica per rendere visibile l'icona it-burger nell'header light.

- docs/menu-di-navigazione/header.md
- src/scss/custom/_header.scss
- src/scss/custom/_navigation.scss
- src/scss/custom/_timeline.scss
Aggiunta z-index al menu e modifica dello z-index dei pin della timeline
Fixes #712
> fix(core):z-index nav and timeline

- src/scss/custom/_steppers.scss
Fix della proprietà display da block ad active della voce attiva dello steppers da breakpoint 992 in su.
Fix dell'ovalizzazione del contenitore del numero step.
Fixes #727
> fix(core): steppers active element on desktop

- src/scss/custom/_card.scss
Fixes #737
Ripristinato il padding a destra e a sinistra di un elemento `card-body` associato ad un elemento `card-img`. Si vedano le immagini allegate alla issue per comprendere l'origine della richiesta.
Se necessario procedo con l'altra soluzione proposta nella issue referenziata.
> fix: restored left and right padding to card-body in a card-img

- Gemfile
- Gemfile.lock
Nel tentativo di eseguire il comando:
```
npm run documentation-serve
```
sul mio ambiente windows, veniva segnalata la necessità di aggiungere un paio di dipendenze (`wdm` e `webrick`) dentro il `Gemfile`: altrimenti non funzionava.
La modifica va ad aggiungere queste dipendenze, vincolandole al fatto che l'ambiente dove viene eseguito il comando sia di tipo windows. 
Ho verificato la modifica su ambiente windows e tramite WSL 2 su Windows 11.
> fix: gem dependencies for windows environment

- docs/esempi/comuni/template-novita-evento.html
- docs/esempi/comuni/template-novita-notizia.html
- docs/esempi/comuni/template-servizi-servizio.html
- src/scss/custom/_grid.scss
Fixes #758
fix: row-column-border, show top border only on large interfaces
spostata una riga di codice per consentire che il bordo superiore venga mostrato solo nelle interfacce con dimensione superiore a `lg` di modo che nelle interfacce con altre dimensioni vengano visualizzati solo i bordi legati alle colonne figlie della row-column-border.
> fix: row-column-border on mobile interfaces

- src/scss/custom/_autocomplete.scss
È stata rimossa la proprietà `display: block` in quanto già presente `display: flex`
> fix: removed duplicate style definitions

- docs/componenti/card.md
Per rappresentare l'aspect ratio propongo l'uso di numeri interi al posto dei decimali, il risultato non cambia ma penso che sia più leggibile.
> Aspect ratio con decimali

- docs/menu-di-navigazione/toolbar.md
Rimosso _aria-hidden="true"_ sui listitem del toolbar e aggiunto _role="separator"_ e _aria-orientation="vertical"_, per essere semanticamente allineati tra struttura che vanno a leggere gli screen reader e vista.
issue di riferimento: https://github.com/italia/bootstrap-italia/issues/796
Testato con NVDA 2022.3
> chora: fix divider accessibility

- docker-compose.yml
- docs/come-iniziare/migrazione-dalla-versione-1.md
Fix issue #830
Aggiornamento per chiarimenti su documentazione con braking per select custom
> [UPD] chiarimenti su documentazione con breaking per select custom

- types/plugins/fonts-loader.d.ts
Rimozione dell'inizializzazione del parametro `path` in `loadFonts`.
Fixes #882
> fix: remove parameter initializer

- src/scss/custom/_steppers.scss
Come segnalato da un utente sul canale `#design-system` dello Slack di Developers Italia, dalla versione 2.3.0 di BI è stata introdotta una regressione (#727).
Questa PR prova a risolvere la regressione facendo in modo che non venga applicato `display: block` allo step attivo.
> fix: remove display block from active step

- src/scss/_variables.scss
This PR fixes the pager link font-weight, now aligned to the new UI kit v3.0 ([see link](https://www.figma.com/file/2gaQw683ZazAPEILQtFLZF/%5BDesign-system-%E2%80%A8del-Paese%5D---UI-Kit-Italia?type=design&node-id=1486%3A101345&t=6aVsFg5cWJ0vOAWg-1))
> fix: pager link font weight

- src/scss/custom/_card.scss
La PR elimina una classe CSS che sovrascriveva il padding orizzontale, eliminandolo, dalle card con immagine
> fix: card with image not having padding around body text

- docs/componenti/alert.md
- src/scss/custom/_alert.scss
Added the `primary` color variant.
> fix: alert color variants

- src/js/plugins/navscroll.js
Fixes #944
ho rimosso anche il fatto che gli effetti di scroll, e tutto il resto ad essi collegati, si attivassero solo dopo che l'utente effettuasse uno scroll della pagina in quanto la cosa crea dei comportamenti inattesi in modalità mobile (se si usa il menu laterale sticky bottom) e non abilita le animazioni.
> nav-link anchor set focus on target

- docs/componenti/progress-indicators.md
- src/scss/custom/_progress-spinners.scss
feat: add sizes large and extra-large to spinner standard and double
Aggiunte nuove dimensioni per "Spinner" e "Spinner doppio", introdotte la dimensione `large` e `extra-large`.
Aggiornata la documentazione aggiungendo una nuova `row` per consentire la visualizzazione delle nuove dimensioni
Fix #1000
> Add new spinner sizes

- docs/componenti/chips.md
- src/scss/_variables.scss
- src/scss/custom/_chips.scss
C'è un bug di allineamento orizzontale quando le Chips sono in gruppo, scoperto sviluppando il sito Designers Italia. Vedi fix temporaneo realizzato qui https://github.com/italia/designers.italia.it/pull/1101
@zetareticoli modifica/integra come credi. E testiamola su tutti i browser/device. 
----
{New PR from the original one here: https://github.com/italia/bootstrap-italia/pull/1020 }
> Fix chips margins

- src/js/plugins/navbar-collapsible.js
I button della navbar (toggle dropdown, toggle megamenu) devono essere "focusable" anche su mobile, nell'ordine corretto.
Nel plugin `navbar-collapsible.js` il `SELECTOR_NAVLINK` può essere anche `<button>`, non solo un `<a>` come adesso. Vedi casi di dropdown e megamenu. 
🔴 È un bug che oggi preveda solo `a.nav-link`: se provi infatti a navigare da tastiera la navbar mobile sei "trapped" sull'icona di chiusura se hai solo buttons nella navbar (es: https://designers.italia.it). E anche ci fossero `a`, salteresti sempre i toggle di tipo `button`.
**In questa PR ho reso agnostico il selettore togliendo il tag `a` e lasciando la sola classe `.nav-link`.** 
🟠 Una alternativa sarebbe avere un selettore multiplo di `a.nav-link` e `button.nav-link` se preferiamo limitare. 
@astagi lascio a te la …
> fix: navbar mobile focus

- src/scss/custom/_type.scss
Remove forced `underline` for links with `.text-decoration-none`. Fixes #1045
> fix: removed forced underline

- src/scss/custom/_bottomnav.scss
In questa PR sono state apportate le seguenti modifiche:
- allineamento del numero all'interno del badge
- corretto il border radius del badge per impedire forme ovali in caso di numeri ridotti
- modificato il sizing, utilizzando `padding` invece che `min-height`
- modificata la posizione del badge alert
> fix: `BottomNav` badge and alert

- src/scss/custom/_form-input-file.scss
Removed a deprecated CSS declaration, used for older IE browsers.
Closes #1098
> fix: remove deprecated declaration

- src/scss/custom/_forms.scss
Corretto il problema del troncamento dell'etichetta di un elemento `legend`.
> fix: legend truncate

- src/js/plugins/form-validate.js
Con questa PR andiamo ad aggiungere un terzo parametro al costruttore della classe FormValidate che viene passato come parametro al costruttore di JustValidate.  
Questo permette di passare a JustValidate un dizionario per messaggi di validazione generici localizzati.
> Feat: aggiunge parametro per dizionario per messaggi di validazione generici localizzati

- Gemfile.lock
- docs/componenti/sections.md
In riferimento alla [issue 1199](https://github.com/italia/bootstrap-italia/issues/1199) ho modificato i vari `aria-describedby` presenti nella pagina della documentazione del componente `Section` in `aria-labelledby` in quanto più aderenti alle linee guida ARIA
> docs: changed aria-describedby to aria-labelledby in the Section component

- docs/form/input-calendario.md
- src/scss/custom/_forms.scss
- src/scss/custom/_just-validate.scss
Per risolvere il problema indicato in #1207 è stato necessario aggiungere la classe `.form-control` al tag `input` di tipo `time` e `date` a cui mancava.
Con l'occasione, è stata fatta pulizia di alcune proprietà duplicate rispetto alla classe `.form-control` ereditata da BS5.
Risolto con l'occasione un bug su tutte le input negli stati `valid` e `invalid` per cui veniva rimosso il colore di sfondo.
> fix: is-invalid state on `input`

- docs/menu-di-navigazione/header.md
- src/scss/custom/_header.scss
Corretta la dimensione dell'elemento `container` in header.
> fix: header container size

- docs/form/input.md
- src/scss/custom/_forms.scss
Aggiunte le classi `.form-control` a tutte le `<input>`.
Aggiunto il disclaimer sulla breaking change della v2.10.0 in merito alle varianti di dimensione `.form-control-lg` e `.form-control-sm`.
> fix: add `.form-control` and disclaimer

- docs/componenti/tab.md
- src/scss/components/_tab.scss
> fix: transform tabs filler from li to div

- docs/come-iniziare/introduzione.md
Corretto un typo nella documentazione della breaking change relativa al focus.
> fix: typo in introduzione

- src/scss/base/_variables.scss
- src/scss/components/_carousel.scss
Ho corretto un errore di battitura nel nome della variabile `$crs-landcape-bottom` in `$crs-landscape-bottom` sia nel file dove definita che dove viene usata. Inoltre ho aggiunto un commento alla variabile `$crs-landcape-card-padding` per identificarla come variabile non usata
> fix: carousel typo

- src/scss/base/_mixins.scss
- src/scss/base/mixins/_focus.scss
- src/scss/bootstrap-italia.scss
- src/scss/utilities/focus.scss
spostati i mixin del focus in un file dedicato, in modo che possano essere importabili e riutilizzabili senza per forza dover importare il file focus.scss che nell'integrazione con i web-components genererebbe problemi di focus.
> chore: refactor focus mixin

- _includes/scripts.html
Dopo l'ultimo aggiornamento il bottone per copiare il codice non visualizza correttamente l'icona a causa di un path errato.
Esempio: https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/
Ho aggiunto `{{ site.baseurl }}`.
> fix(docs): path errato nel bottone per copiare il codice

- docs/esempi/form/index.html
- src/scss/forms/_form-control.scss
- src/scss/forms/_form-input-number.scss
sistemati gli stili durante la validazione dei campi di tipo number input
e lo stato readonly dei campi di tipo number input
> fix: numberinput validation styles and readonly styles
