docs/utilities/flex.md
docs/utilities/griglie.md

Traduzione Issue #13 Flex

---

_data/nav.yml
docs/utilities/introduzione.md
docs/utilities/media-object.md

Issue #10 - Media objects e componenti di layout

---

_data/nav.yml
_includes/footer.html
docs/assets/src/scss/_footer.scss
docs/come-iniziare/introduzione.md
docs/informazioni.md

Aggiunta pagina informativa, piccolo fix sull'accessibilità

---

docs/assets/src/scss/_component-examples.scss
docs/componenti/bottoni.md
src/scss/custom/_buttons.scss
src/scss/custom/mixins/_buttons.scss
src/scss/utilities/focus.scss

Allineati alcuni colori e dimensioni al design-kit.

Revisione colori e dimensioni bottoni, rimosse temporaneamente regole per focus

---

src/scss/_variables.scss
src/scss/bootstrap-italia.scss
src/scss/custom/_type.scss

Aggiunta font-family Lora

---

src/js/plugins/custom-select.js

Fix select label positioning #156

---

gulpfile.js
package-lock.json
package.json

A quick fix on a couple of npm packages

gulp-wrapper fix

---

docs/componenti-aggiuntivi/back-to-top.md
package-lock.json
src/scss/custom/_back-to-top.scss

Sostituzione dell'icona contenuta nel back to top.
Sostituzione dell'icona da it-collapse a it-arrow-up.
Fine tuning dimensioni.

Hotfix icona back to top

---

_data/nav.yml
docs/utilities/history-back.md
gulpfile.js
src/js/plugins/history-back.js

Utility "History Back". JS ed HTML documentazione.
Aggiunta del js history-back.js nei plugin ed inclusione in gulpfile.js.
Aggiunta della pagina "History back" alla documentazione e inclusione della stessa nel nav.yml.

Utility "History back". JS ed HTML documentazione.

---

_data/nav.yml
docs/componenti-aggiuntivi/callout.md
docs/componenti/dropdown.md
src/scss/bootstrap-italia.scss
src/scss/custom/_callout.scss

Sviluppo HTML, SCSS e documentazione per componente Callout.
- HTML e documentazione
- SCSS per stile basico e varianti
- Inclusione di un Collapse standard per la variante "Approfondimento"
- Aggiunta della voce Callout a nav.yml

#169 Callout

---

CONTRIBUTING.md
Gemfile
Gemfile.lock
PULL_REQUEST_TEMPLATE.md
README.md
_includes/docs-navbar.html
_includes/docs-topbar.html
_includes/footer.html
docs/assets/src/scss/_brandhead.scss
docs/come-iniziare/modificare-componenti.md
docs/componenti-aggiuntivi/introduzione.md
docs/componenti/introduzione.md
docs/informazioni.md
docs/utilities/colori.md
index.html

Fix links Docs Italia, icone ed altri dettagli in homepage.

---

_includes/docs-sidebar.html
docs/assets/src/scss/_sidebar.scss

Ripulito menu principale della documentazione.

Nuovo stile menu

---

_includes/cookiebar.html
docs/componenti-aggiuntivi/cookiebar.md
docs/esempi/cookiebar/index.html
src/scss/custom/_cookiebar.scss

Restyling Cookie Bar.
HTML, SCSS, Docs, Review accessibilità.
- Modifica file src\scss\custom\_cookiebar.scss
- Aggiornamento docs\componenti-aggiuntivi\cookiebar.md
- Aggiornamento _includes\cookiebar.html

Cookiebar: HTML, SCSS, Docs, Review accessibilità

---

_config.yml
_data/examples.yml
_includes/footer.html
docs/come-iniziare/introduzione.md
docs/come-iniziare/modificare-componenti.md
docs/componenti/introduzione.md
docs/informazioni.md
gulpfile.js
package-lock.json
package.json
src/js/bootstrap-italia.js
src/scss/bootstrap-italia.scss
src/scss/custom/_chips.scss

Aggiornamento libreria Bootstrap alla più recente versione 4.2.1.
Fix #257

Update to bootstrap 4.2.1

---

src/js/plugins/cookiebar.js

Issue including Utils in Cookiebar

---

src/scss/custom/_navigation.scss

Fix two colors for the same background

---

src/js/plugins/forms.js

Fixes #269 
Ho modificato le condizioni che andavano a valutare se il placeholder era valorizzato.
Ho usato la classica tecnica del !! che considera false i seguenti valori: undefined, null e ''
era pure usata da voi in un solo caso.
- [x ] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [x ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).

gestisco i casi in cui il placeholder è stringa vuota

---

src/scss/custom/_autocomplete.scss

Fix autocomplete icon padding

---

docs/esempi/template-vuoto/index.html
docs/menu-di-navigazione/header.md
src/scss/custom/_headerslim.scss
src/scss/custom/_headerslimtheme.scss

Modificato markup e stile dell'elemento con classe "nav-mobile" nella sezione Header per essere valido secondo le specifiche W3C
- [x ] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [x ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [x ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [x ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/serv …

Header W3C compliant

---

docs/assets/src/scss/_component-examples.scss
src/js/plugins/forms.js
src/scss/custom/_autocomplete.scss
src/scss/custom/_form-password.scss
src/scss/custom/_form-toggles.scss
src/scss/custom/_forms.scss

Fix label overlapping for input with buttons

---

.circleci/config.yml

Removed aliases

---

docs/form/select.md
src/js/plugins/select.js

Funzione per la reinizializzazione delle select
- [ x] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [ x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
Na
- [x ] La documentazione è stata aggiornata.

Select reinit

---

docs/form/introduzione.md

Typo nel paragrafo Validazione, sezione Form.

typo in validation paragraph

---

src/scss/custom/_headerslim.scss
src/scss/custom/_navigation.scss

Small fixes in the navbar

---

src/js/plugins/password-strength-meter/password-strength-meter.js

This is useful if you need to get the element via CSS selectors.

Add a class to the password-strength-meter

---

docs/menu-di-navigazione/bottomnav.md
docs/menu-di-navigazione/toolbar.md

Fix voiceover for bottombar and toolbar components

---

src/scss/custom/_forms.scss

Per le etichette degli input:
- imposta la larghezza massima tenendo conto della presenza di un'icona
- imposta lo spostamento a destra solo se presente un'icona

Adjust label position and max-width only if needed

---

src/js/plugins/select.js

Update to the fixes for a11y done on bootstrap-select version 1.13.10

Updates to a11y fixes for bs-select v1.13.10

---

docs/assets/src/scss/_nav.scss
src/scss/custom/_back-to-top.scss
src/scss/custom/_form-datepicker.scss

Sono stati rimossi i non-breking spaces aggiunti in alcuni file scss, come descritto nella issue #346.
Fixes #346.

Rimossi non-breaking spaces dai file scss nel sorgente

---

_includes/esempi/comuni/footer.html

Inseriti i componenti richiesti nel file `footer` incluso in `_includes`
Fixes #357

aggiunta della 'cookie bar' e del tasto 'torna su' come richiesto da #357

---

_data/examples.yml
docs/esempi/template-singolo-argomento/index.html
src/scss/bootstrap-italia.scss
src/scss/custom/_badge.scss
src/scss/custom/_card.scss
src/scss/custom/_grid.scss
src/scss/custom/_hero.scss
src/scss/custom/_type.scss

Prima proposta per la pagina **Singolo Argomento** come da mockup InVision.

proposta #1 pagina singolo argomento

---

docs/esempi/template-lista-argomenti/index.html
docs/esempi/template-novita/index.html
docs/esempi/template-singolo-argomento/index.html

Correzione path SVG in `lista argomenti` e `singolo argomento`

fixing bug #363 path SVG

---

src/scss/custom/_form-select.scss

Remove box shadow when using form-control class

---

src/js/plugins/datepicker/locales/it.js

Fix date label

---

_includes/esempi/comuni/header.html
docs/esempi/template-vuoto/index.html
docs/menu-di-navigazione/header.md
src/scss/_variables.scss
src/scss/custom/_headerslim.scss
src/scss/custom/_headerslimtheme.scss
src/scss/custom/_linklist.scss
src/scss/custom/_navigation.scss
src/scss/custom/_tab.scss
src/scss/utilities/colors.scss
src/scss/utilities/colors_vars.scss

Fix #392 
Permette la modifica del colore nell'header, e sistema un po' di duplicazioni nei nomi di colori e delle variabili colore.

[WIP] Header and colours cleanup

---

src/scss/custom/_avatar.scss

To prevent image from taking undesired shape

Fix Issue #404 : Add border-radius of 50% to Avatar image

---

src/scss/utilities/focus.scss

Vedi https://github.com/twbs/bootstrap/blob/258a56b473edea843eb20e80bbc7bf49eb040a32/scss/_reboot.scss#L58

No box shadow in not keyboard-focusable elements

---

docs/form/introduzione.md

Correzione di un errore ortografico sulla documentazione
- [ x] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [ x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ x] La documentazione è stata aggiornata.

fix typo in docs

---

src/scss/custom/_back-to-top.scss
src/scss/custom/_dialog.scss
src/scss/custom/_tab.scss

Fix minori relativi ad alcuni valori di proprietà CSS.

Fix css validation errors

---

docs/componenti/sections.md

Fix typo in "Section" component example. Fixes #438.

Fix typo in "Section" component example

---

_data/progetti.yml

Fixing Comune di Ala link. @francescozaia

Fix link Comune di Ala

---

docs/componenti/swiper.md

Typo review and fix various mistake.

Typo review and fix various mistake.

---

docs/componenti/swiper.md

Rimozione variabile obsoleta e correzione errore ortografico (#488 e https://github.com/italia/bootstrap-italia/pull/481#discussion_r498290379)

Rimozione variabile obsoleta ed errore ortografico

---

src/scss/bootstrap-italia.scss

Update import swiper module
Come da https://github.com/italia/bootstrap-italia/pull/481#discussion_r498287910 ho cambiato l'import del pacchetto swiper da css compilato ai singoli scss.
Ho compilato e caricato questa patch su questo indirizzo https://bi-branch-swiper.arturu.it/docs/componenti/swiper/

Update import swiper module

---

docs/form/select.md

Piccolo typo nella documentazione della select
--

Fixing typo in select doc

---

_includes/footer.html

Fix broken links (privacy policy, legal notice)

---

package-lock.json
package.json

Utilizzo del pacchetto condiviso per la lista di browsers supportati.

Uso del pacchetto browserslist condiviso

---

docs/form/introduzione.md
docs/form/select.md

Aggiunto gli attributi "for" alle label e l'attributo "id" alle select.
Fixes #532 & #547
- [ X] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).

docs(a11y): select label association

---

src/scss/custom/_tooltip.scss

fix(core,a11y): increase tooltip font size

---

docs/form/input-calendario.md
docs/form/input-ora.md
docs/form/input.md
docs/form/introduzione.md

Ordine corretto dei tag "label"

docs: label & input order

---

src/js/plugins/forms.js
src/scss/custom/_forms.scss

Rimozione delle funzioni che forzavano le larghezze dei tag "label"
Fixes #526, #429, #450

fix(core): remove label forced width

---

src/scss/custom/_form-datepicker.scss
src/scss/custom/_forms.scss

Fixes #486
Risolve punto 2: componenti button mancano di focus highligh in alcuni casi

fix(core,a11y): input-group button and datepicker focus status

---

docs/esempi/navscroll/index.html
src/js/plugins/navscroll.js
src/scss/custom/_navscroll.scss

Correzione enfatizzazione dell'elemento attivo nella navscroll al click.
Correzione z-index per il funzionamento nei vari contesti
Correzione link errato nella documentazione

fix(core,docs): enfatizzazione corretta elemento attivo

---

docs/componenti/card.md

E' stata inserito nella documentazione l'esempio per renderizzare correttamente un link con classe .btn

docs: aggiunto esempio corretto di link con classe btn nelle card

---

_includes/example.html
_plugins/regex_filter.rb

This should fix #495 and allow to read example correctly

feat: add regex_filter for templates

---

src/scss/_variables.scss
src/scss/utilities/colors_vars.scss

Fixes #474
Aggiunta flag default alle variabili:
- $btn-primary-bg
- $btn-primary-border
- $link-color
E alle variabili di tutti i colori custom contenuti in scss\utilities\colors_vars.scss

fix(core): add default to link custom colors and button sass variables

---

src/scss/_variables.scss

Fixes #516 
Aggiunto il flag !default a tutte le variabili colore di `_variables.scss`.

fix(core): added default to all scss color variables

---

docs/componenti/dropdown.md
src/scss/custom/_dropdown.scss

Fix #496 
Aggiunto alla documentazione dei dropdown le opzioni di posizionamento e creato gli stili per la corretta renderizzazione.

fix(core,docs): dropdown positions

---

docs/form/input-numerico.md
src/js/plugins/input-number.js

Discrezionato js che veniva applicato anche su firefox e non solo su ie

fix(core): firefox input number bug

---

_config.yml
docs/come-iniziare/introduzione.md
docs/come-iniziare/strumenti-di-compilazione.md

Aggiunto il flow, docker e fatto qualche fix nella parte introduttiva

feat: add docker and contribution steps

---

_includes/docs-navbar.html
index.html

feat: add bootstrap-italia current version to home page

---

docs/form/input-numerico.md
src/js/plugins/input-number.js

fix(core): emit change on numeric steppers

---

docs/componenti/collapse.md
gulpfile.js
src/js/plugins/collapse.js

Implementazione delle keyboard interaction degli Accordion/Collapse come da WAI-ARIA best practices:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

fix(core,a11y): accordion and collapse keyobard interaction

---

src/js/plugins/sticky-header.js

Correzione errore di rimozione classe CSS durante il passaggio allo stato fixed dello sticky header

fix(core): fix remove css class error in sticky header

---

_includes/esempi/comuni/header.html

Correzione url icone dell'header

docs: svg url

---

_includes/scripts.html
docs/esempi/template-home-page/index.html
docs/esempi/template-novita-evento/index.html

Attivazione owl carousel in pagine comuni

fix(docs): enable carousel

---

src/js/plugins/carousel-legacy.js

fix(core): dots length in aria label

---

src/scss/bootstrap-italia.scss
src/scss/custom/_bootstrap-select.scss

Remove scss warning for bs-select component

fix: remove scss deprecation warning for bs select

---

docs/form/input-numerico.md
src/js/plugins/input-number.js

Add digits attribute to display and approximate values correctly

fix: step with decimals in numerical input

---

src/js/plugins/dropdown.js

fix: dropdown do not work on window resize

---

docs/esempi/template-comuni-vuoto/index.html
src/js/plugins/sticky-header.js
src/scss/custom/_header.scss

fix: target with sticky header

---

publiccode.yml

Add publiccode.yml to be listed in Developer Italia's Catalog

publiccode.yml for Bootstrap Italia

---

publiccode.yml

feat: PNRR tags for the catalog

---

_includes/docs-sidebar.html
src/scss/custom/_sidebar.scss

fix(core,docs): icon right style

---

docs/esempi/comuni/template-novita-notizia.html
src/scss/custom/_grid.scss
src/scss/custom/_navigation.scss

fix(core,example): sidebar collapsable  mobile

---

docs/componenti/chips.md
docs/esempi/comuni/template-amministrazione.html
src/scss/custom/_chips.scss

Aggiunta di classe alert e attributo data-bs-dismiss='alert' all'elemento Chip
fix #683

fix: dismissable chip

---

.github/PULL_REQUEST_TEMPLATE.md
README.EN.md
_config.yml
docs/come-iniziare/modificare-componenti.md
docs/componenti/introduzione.md
docs/utilities/colori.md
index.html
package.json
publiccode.yml

Update lg + manuale link

---

src/scss/custom/_type.scss

Rimozione bordo cyan da elementi simple e dark con allineamento a destra
Fixes #704

fix(core): rimozione border su elementi dark e card simple

---

src/scss/custom/_timeline.scss

FIx comportamento errato della timeline nei breackpoint bassi.
Fixes #708

fix(core): timeline fix

---

src/scss/custom/_timeline.scss

fix(core): timeline elements spaces

---

publiccode.yml

chore: fix versions in publiccode

---

docs/componenti/cookiebar.md

Update cookiebar.md: "updating content" message

---

src/scss/custom/_buttons.scss

Changed button outline secondary shadow #747

---

src/js/plugins/navbar-collapsible.js

fix(a11y): focus on close button when opening the nav menu on mobile

---

src/js/plugins/navbar-collapsible.js
src/js/plugins/util/pageScroll.js
src/scss/bootstrap-italia-comuni.scss
src/scss/bootstrap-italia.scss
src/scss/custom/_page-scroll.scss

fix(a11y): prevented page scroll when nav menu is opened

---

docs/organizzare-gli-spazi/introduzione.md

documentate classi contenitore (issue #741)

---

docs/organizzare-gli-spazi/introduzione.md

Dopo aver creato una PR riguardante la issue #741 , mi sono accorto di un errore ortografico che ho tempestivamente corretto.

docs:fix spelling error

---

src/scss/custom/_form-datepicker.scss

Fixes #799 
Per la correzione del suddetto bug segnalato da @AlessandroVecchi è stato necessario eliminare dal file '_form-datepicker.scss' il seguente codice:
`
abbr[data-original-title],
abbr[title] {
text-decoration: none;
cursor: default;
} 
`
eseguendo il comando `npm run build`, i file CSS vengono generati correttamente.

Fix issue #799

---

docs/componenti/dimmer.md
docs/esempi/comuni/template-amministrazione.html
docs/esempi/comuni/template-documenti.html
docs/esempi/comuni/template-homepage.html
docs/esempi/comuni/template-novita-evento.html
docs/esempi/comuni/template-novita.html
docs/esempi/comuni/template-servizi.html

Questa PR va a fixare gli errori presi mentre si fanno i controlli: _Test project / Pa11y tests (pull_request)_.

fix: pa11y error

---

package.json

The main attribute in package.json should point to the UMD library version. Currently it points to a non-existing file.
Fixes #808.

fix: main entry points to a non-existing file

---

docs/organizzare-gli-spazi/griglie.md

Fixed wrong container max-width for XL breakpoint

Fixed wrong container max-width for XL breakpoint

---

src/scss/custom/_steppers.scss

fix: stepper borders

---

docs/componenti/video-player.md

Added chapter: Subtitles, captions, chapters and descriptions

chore(docs): add assistive text

---

docs/form/select.md

rimozione caratteri non necessari nel file select.md ->  ```

rimozione caratteri non necessari nel file select.md

---

src/scss/custom/_tab.scss

Come richiesto nella suddetta issue, ho aperto questa PR per la correzione.
Per eventuali problemi sono a disposizione!

fix: issue #851

---

_data/progetti.yml

Ho aggiornato le versioni drupal supportate dal tema generico euna modifica alla descrizione

Fix: update progetti.yml

---

docs/componenti/buttons.md
docs/organizzare-i-contenuti/tipografia.md

chore(docs): fix toc in typography

---

docs/componenti/carousel.md
docs/form/input.md
src/js/plugins/carousel-bi.js
src/scss/_variables.scss
src/scss/custom/_buttons.scss
src/scss/custom/_carousel.scss
src/scss/custom/_timeline.scss
src/scss/custom/_type.scss

Questa PR contiene una serie di fix di allineamento al Design Kit per Bootstrap Italia.

fix: carousel single slide wrapper background

---

docs/assets/src/scss/_component-examples.scss
docs/componenti/buttons.md
src/scss/custom/_buttons.scss

Fix: buttons

---

docs/componenti/callout.md
src/scss/custom/_callout.scss

fix: callout background with pseudo elements

---

docs/componenti/video-player.md

chore: video player example API names

---

docs/componenti/video-player.md

fix: video absolute path

---

.github/PULL_REQUEST_TEMPLATE.md
README.EN.md
README.md

Aggiornati i link a Boostrap versione 5.2 per allinearsi alla versione attualmente usata. Rif: [66fd71d](https://github.com/italia/bootstrap-italia/commit/66fd71d127d0184aab7c9771cf1caee1f7e96d36)

docs: update Bootstrap documentation links

---

docs/componenti/video-player.md

chore(docs): add youtube plugin warning

---

src/scss/utilities/colors_vars.scss

Assigned `$primary-` color variables to footer in order to change footer color when theming.
Fixes #893

fix: footer color variables #893

---

docs/componenti/buttons.md
src/scss/_functions.scss
src/scss/custom/_buttons.scss
src/scss/custom/mixins/_buttons.scss

Added status colors variations for button outline.
Fixed a bug on button outline border size when active.
Resolves #899.

feat: buttons outline color variations

---

src/js/plugins/navscroll.js

fix: navscroll content checking

---

src/js/plugins/input-label.js

fix: escape selector when getting label

---

_includes/esempi/comuni/area-personale/documenti.html
_includes/esempi/comuni/area-personale/messaggi.html
_includes/esempi/comuni/area-personale/pagamenti.html
_includes/esempi/comuni/area-personale/pratiche.html
_includes/esempi/comuni/area-personale/scadenze.html
docs/componenti/badge.md
src/scss/_variables.scss
src/scss/bootstrap-italia-comuni.scss
src/scss/custom/_badge.scss
src/scss/custom/_megamenu.scss
src/scss/utilities/text-colors.scss

fix: remove text colors darken

---

docs/organizzare-gli-spazi/bordi.md
docs/organizzare-i-contenuti/tipografia.md

Alcuni minor fix su nomi degli esempi.

fix: example names

---

docs/esempi/form/index.html
docs/form/introduzione.md
package-lock.json
package.json

- Aggiornato il pluging "just-validate" all'ultima versione (4.2.0).
- Corretti alcuni errori nella pagina di esempio validazione
- Aggiunta funzione onSuccess nella documentazione

Update just validate to 4.2.0

---

src/scss/custom/_forms.scss

fix: radio and checkbox selection

---

docs/componenti/video-player.md
src/js/plugins/accept-overlay.js
src/scss/_variables.scss
src/scss/custom/_accept-overlay.scss
src/scss/custom/_linklist.scss

Alcuni importanti fix sul `video player`:
- Opacità overlay
- Swap pulsante/checkbox overlay
- Altezza overlay su Firefox (+Firefox mobile)

Fix: video player overlay

---

docs/componenti/video-player.md

Due fix per allinearsi ai lavori in corso su Designers Italia cc @astagi

fix: player video content

---

src/scss/_variables.scss

Fixed the max-width for `.container-md` breakpoint.

fix: container-md max width

---

docs/menu-di-navigazione/footer.md

feat: aggiunti nomi API per i due esempi del componente Footer

---

src/scss/custom/_videoplayer.scss

fix: hide unecessary video controls on mobile

---

docs/organizzare-i-contenuti/tabelle.md

chore(docs): responsive tables

---

docs/componenti/tab.md

chore(docs): add warning and remove selection functionality in tabs

---

src/scss/custom/_tab.scss

fix(a11y): focus selector for tabs

---

src/scss/custom/_chips.scss

fix: chips margin

---

docs/assets/src/scss/_syntax.scss
src/scss/custom/_videoplayer.scss

fix: video js bar popup elements

---

src/scss/custom/_forms.scss

Fixes https://github.com/italia/design-angular-kit/issues/277

fix: active label input group

---

_includes/scripts.html

Successivamente alla modifica dello style del codice (#1031), il bottone copia codice copiava anche il numero delle righe:
```
1
2
3
4
5
<span class="border"></span>
<span class="border-top"></span>
<span class="border-end"></span>
<span class="border-bottom"></span>
<span class="border-start"></span>
```
Dopo la modifica:
```
<span class="border"></span>
<span class="border-top"></span>
<span class="border-end"></span>
<span class="border-bottom"></span>
<span class="border-start"></span>
```

fix: corretto bottone copia, escludo il numero della riga

---

docs/esempi/form/index.html
docs/esempi/navscroll/index.html
docs/esempi/template-vuoto/index.html
docs/form/input.md
docs/form/introduzione.md
src/scss/custom/_forms.scss
src/scss/custom/_just-validate.scss

Breaking change on input with prepend icon

feat: new input with prepend icon

---

CONTRIBUTING.md

Corretto il link relativo a `Convention commits`.

fix: closing brackets

---

docs/form/introduzione.md

Corretto id nell'esempio della validazione

fix: id form in onSuccess validation method

---

src/scss/custom/_callout.scss

Corregge il bug del titolo che si sovrappone con il bordo superiore.

fix: `callout` title size

---

docs/componenti/rating.md

Updated the `Rating` description using the same text as published in https://designers.italia.it/design-system/componenti/rating/

content: `Rating` description

---

src/js/plugins/backToTop.js
src/js/plugins/cookiebar.js
src/js/plugins/fonts-loader.js
src/js/plugins/form-validate.js
src/js/plugins/input-number.js
src/js/plugins/input-password.js
src/js/plugins/input-search-autocomplete.js
src/js/plugins/input.js
src/js/plugins/masonry.js
src/js/plugins/navscroll.js
src/js/plugins/select-autocomplete.js
src/js/plugins/sticky.js
src/js/plugins/track-focus.js
src/js/plugins/upload-dragdrop.js
src/js/plugins/util/on-document-scroll.js
src/js/plugins/util/pageScroll.js
src/js/plugins/util/tween.js
src/js/plugins/util/youtube-video.js

fix: check document presence

---

src/js/plugins/form-validate.js
src/js/plugins/history-back.js
src/js/plugins/init.js
src/js/plugins/masonry.js
src/js/plugins/sticky.js
src/js/plugins/util/device.js
src/js/plugins/videoplayer.js

fix: check window presence

---

docs/esempi/sticky/index.html
src/scss/custom/_sticky.scss

Rivedere il funzionamento dello stack `z-index`.
#1009
#1104

fix: `z-index` stack

---

src/js/plugins/select-autocomplete.js

fix(a11y): select autocomplete italian messages by default

---

docs/form/checkbox.md
docs/form/radio-button.md
docs/form/toggles.md

feat: groups rewrite

---

package-lock.json
package.json

chore: upgrade rollup

---

docs/menu-di-navigazione/footer.md
src/scss/custom/_footer.scss

fix: footer link decoration

---

src/scss/custom/_footer.scss

fix: footer inner elements size

---

docs/componenti/avatar.md
src/scss/custom/_avatar.scss

Fixed avatar indentation code and styles.

fix: avatar styles

---

docs/esempi/form/index.html

chore: fix groups example

---

docs/componenti/chips.md
docs/utilities/icone.md

fix: docs refuses

---

src/scss/forms/_form-control.scss

fix: text area border

---

docs/menu-di-navigazione/toolbar.md
src/scss/components/_toolbar.scss

fix: badge position in toolbar and bottomnav

---

docs/componenti/steppers.md
src/scss/components/_steppers.scss

fix: steppers icons

---

docs/esempi/form/index.html
docs/form/input-numerico.md
src/scss/forms/_forms.scss

fix: add input-symbol-label

---

docs/form/input.md

fix(a11y): add aria hidden to icons and warnings

---

docs/assets/src/scss/docs.scss
rollup.config.mjs

chore: speedup rollup

---

docs/componenti/avatar.md
src/scss/base/_root.scss
src/scss/components/_avatar.scss

Applica i design tokens al componente avatar.

refactor: design tokens in avatar

---

docs/organizzare-i-contenuti/liste-di-immagini.md

docs: add warning on images list

---

docs/form/input.md

docs: improve breaking message on input

---

package-lock.json
package.json

chore(deps): upgrade video.js

---

src/scss/bootstrap-italia.scss
src/scss/components/_header.scss
src/scss/components/_nav.scss
src/scss/components/_navigation.scss

Implementazione dei design tokens in tutti i componenti di navigazione.
Mergia in #1329 perché navbar è parte di header.

feat: navigation tokens

---

docs/esempi/header/header-light.html
docs/esempi/header/index.html
src/scss/base/_root.scss
src/scss/bootstrap-italia.scss
src/scss/components/_header.scss
src/scss/components/_headercenter.scss
src/scss/components/_headernavbar.scss
src/scss/components/_headernavbartheme.scss
src/scss/components/_headerslim.scss
src/scss/components/_nav.scss
src/scss/components/_navigation.scss

Refactoring del codice CSS del componente header che prevede adozione delle custom properties per gestire le proprietà fondamentali del componente e integrazione dei design tokens.
Riduce la specificità dei selettori, riducendo i livelli di indentazione.

feat: header refactoring and design tokens

---

src/scss/components/_buttons.scss

fix: button icon content

---

src/scss/base/_root.scss
src/scss/base/_variables.scss
src/scss/components/_hero.scss

Implementazione dei design tokens nel componente hero.

feat: hero tokens

---

src/js/plugins/track-focus.js
src/scss/components/_navigation.scss
src/scss/components/_tab.scss
src/scss/forms/_form-input-number.scss
src/scss/forms/_form-input-upload.scss
src/scss/forms/_form-toggles.scss
src/scss/forms/_forms.scss
src/scss/forms/_just-validate.scss
src/scss/utilities/focus.scss

Fixes https://github.com/italia/design-react-kit/issues/1150

fix: use data to set focus instead of class

---

src/scss/components/_accordion.scss

Implementazione design tokens in accordion.

feat: accordion tokens

---

docs/componenti/alert.md
docs/componenti/badge.md
src/scss/base/_maps.scss
src/scss/base/_variables.scss
src/scss/components/_alert.scss
src/scss/components/_back-to-top.scss
src/scss/components/_badge.scss

Implementazione dei design tokens per i componenti alert, anchor, back e badge.

feat: alert, anchor, back, badge tokens

---

docs/menu-di-navigazione/navscroll.md
src/scss/base/_reboot.scss
src/scss/base/_variables.scss
src/scss/bootstrap-italia.scss
src/scss/components/_header.scss
src/scss/components/_linklist.scss
src/scss/components/_navbar.scss
src/scss/components/_navigation.scss
src/scss/components/_navscroll.scss
src/scss/components/_navscrolltheme.scss

feat: navscroll design tokens

---

src/scss/forms/_forms.scss

fix: form-check radio and checkbox items line height

---

docs/componenti/modale.md
src/scss/base/_variables.scss
src/scss/components/_modal.scss

Implementazione design tokens nel componente modal.

feat: modal tokens

---

docs/form/input-numerico.md
docs/form/input.md
src/js/plugins/input-label.js
src/js/plugins/input-number.js

fix: input number in firefox

---

docs/componenti/callout.md
docs/componenti/chips.md
docs/esempi/callout/index.html
src/scss/base/vendor/_tokens.scss
src/scss/bootstrap-italia.scss
src/scss/components/_calendar.scss
src/scss/components/_callout.scss
src/scss/components/_chips.scss

Implementazion design tokens nei componenti calendar, callout, chips.

feat: calendar, callout and chips tokens

---

docs/esempi/header/index.html
docs/menu-di-navigazione/header.md
docs/menu-di-navigazione/megamenu.md
src/scss/base/_root.scss
src/scss/base/_utilities.scss
src/scss/bootstrap-italia.scss
src/scss/components/_buttons.scss
src/scss/components/_dropdown.scss
src/scss/components/_header.scss
src/scss/components/_headercenter.scss
src/scss/components/_headerslim.scss
src/scss/components/_megamenu.scss
src/scss/components/_navbar.scss
src/scss/components/_navigation.scss

Implementazione design token in megamenu

feat: megamenu design token

---

docs/menu-di-navigazione/footer.md
src/scss/base/_root.scss
src/scss/bootstrap-italia.scss
src/scss/components/_footer.scss

Implementazione dei design tokens nel componente footer

feat: design tokens in footer

---

docs/componenti/sections.md
src/scss/components/_sections.scss

Implementazione design tokens in sections

refactor: section variables and styles

---

docs/menu-di-navigazione/breadcrumbs.md
src/scss/components/_breadcrumb.scss

feat: breadcrumb design tokens

---

docs/esempi/navscroll/index.html

docs: add header to navscroll example

---

docs/componenti/card.md

chore(docs): fix link in cards

---

_includes/scripts.html

fix: copy icon

---

_includes/example.html
_includes/scripts.html

fix: copy icon path in example html

---

rollup.config.mjs
src/scss/components/_card.scss

Corregge la visualizzazione degli angoli arrotondati nelle varianti di card.
@astagi Ho aggiunto un fix al file `rollup.config` per correggere un problema di ricaricamento del browser nello sviluppo locale. Verifica se è corretto.

fix: card rounded corners
